app = "sporttactic-api"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "npx prisma migrate deploy"

[env]
  PORT = "8000"
  NODE_ENV = "production"
  COOKIE_SAMESITE = "None"
  COOKIE_SECURE = "true"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    grace_period = "20s"
    interval = "30s"
    method = "GET"
    path = "/api/health"
    timeout = "5s"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
